services:
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: whispering-database
  test-db:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGODB_DATABASE: whispering-database-test
